### ISSUE TITLE
Can't tab into MainMenu buttons

### ISSUE THREAD

**Issue by hilgejef** [gaglianr/CS419CapstoneProject#3]
MainMenu can't be accessed by tabbing -- this is because tabbing only cycles through CurrentScreen.  This means that MainMenu is inaccessible.

**Comment by gaglianr** [comment]
You do not use tab to enter the menu.  Main menu is accessed by CTRL+M, or whatever we decide in the Core. Once in the menu, you can use tab, and the CTRL+M or whatever we decide to exit back to the screen.
